version: '3.8'

services:
  motus-app1:
    build:
      context: ./motus
    ports:
      - "3000:3000"

  motus-app2: 
    build: ./motus
    ports:
      - "4000:3000"

  haproxy:
    build: ./motus/haproxy
    ports:
      - "8080:80"
    depends_on:
      - motus-app1
      - motus-app2
  
  auth_in_motus:
    build: ./authentification
    ports:
      - "5001:5001"

  score:
    build: ./score
    ports:
      - "5000:5000"
    depends_on:
      - motus-app1
      - motus-app2
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
    depends_on:
      - redis

volumes:
  redis-data:



