version: '3.8'

services:
  motus-app1:
    build:
      context: ./motus
    ports:
      - "3000:3000"

  motus-app2: 
    build: ./motus
    ports:
      - "4000:3000"

  haproxy:
    build: ./motus/haproxy
    ports:
      - "8080:80"
    depends_on:
      - motus-app1
      - motus-app2
  
  auth:
    build: ./authentification
    ports:
      - "9000:9000"
    depends_on:
      - motus-app1
      - motus-app2

  score:
    build: ./score
    ports:
      - "5000:5000"
    depends_on:
      - motus-app1
      - motus-app2
  redis_score:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-score-data:/data
  
  redis_auth:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-auth-data:/data

  redis_session:
    image: redis:latest
    ports:
      - "6381:6379"
    volumes:
      - redis-session-data:/data
  
volumes:
  redis-score-data:
  redis-auth-data:
  redis-session-data:
  



