version: '3.8'

services:
  motus-app1:
    build:
      context: .
    ports:
      - "3000:3000"

  motus-app2: 
    build: .
    ports:
      - "4000:3000"

  haproxy:
    build: ./haproxy
    ports:
      - "8080:80"
    depends_on:
      - motus-app1
      - motus-app2

